spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:inventory
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

grpc:
  server:
    port: 8000

logging:
  level:
    com.alviss.order_processing: DEBUG
